### ISSUE TITLE
server crashes

### ISSUE THREAD

**Issue by Glucy-2** [2No2Name/hopperOptimizations#16]
The server crashes when a player destroyed a hopper.
````java
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 20-8-2 下午8:26
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 54
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at net.minecraft.class_2371.get(class_2371.java:46)
	at hopperOptimizations.utils.inventoryOptimizer.InventoryOptimizer.getSlot(InventoryOptimizer.java:158)
	at hopperOptimizations.utils.inventoryOptimizer.InventoryOptimizer.findInsertSlot(InventoryOptimizer.java:440)
	at hopperOptimizations.utils.inventoryOptimizer.DoubleInventoryOptimizer.findInsertSlot(DoubleInventoryOptimizer.java:69)
	at net.minecraft.class_2614.handler$zpa000$optimizeInsert(class_2614.java:1310)
	at net.minecraft.class_2614.method_11246(class_2614.java:155)
	at net.minecraft.class_2614.method_11243(class_2614.java:122)
	at net.minecraft.class_2614.method_16896(class_2614.java:109)
	at net.minecraft.class_1937.method_18471(class_1937.java:552)
	at net.minecraft.class_3218.method_18765(class_3218.java:423)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.class_3176.method_3813(class_3176.java:306)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.server.MinecraftServer.handler$zjb000$modifiedRunLoop(MinecraftServer.java:3796)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:653)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at net.minecraft.class_2371.get(class_2371.java:46)
	at hopperOptimizations.utils.inventoryOptimizer.InventoryOptimizer.getSlot(InventoryOptimizer.java:158)
	at hopperOptimizations.utils.inventoryOptimizer.InventoryOptimizer.findInsertSlot(InventoryOptimizer.java:440)
	at hopperOptimizations.utils.inventoryOptimizer.DoubleInventoryOptimizer.findInsertSlot(DoubleInventoryOptimizer.java:69)
	at net.minecraft.class_2614.handler$zpa000$optimizeInsert(class_2614.java:1310)
	at net.minecraft.class_2614.method_11246(class_2614.java:155)
	at net.minecraft.class_2614.method_11243(class_2614.java:122)
	at net.minecraft.class_2614.method_16896(class_2614.java:109)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.class_2614
	Block: Block{minecraft:hopper}[enabled=true,facing=east]
	Block location: World: (247,51,221), Chunk: (at 7,3,13 in 15,13; contains blocks 240,0,208 to 255,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{minecraft:hopper}[enabled=true,facing=east]
	Block location: World: (247,51,221), Chunk: (at 7,3,13 in 15,13; contains blocks 240,0,208 to 255,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.class_1937.method_18471(class_1937.java:552)
	at net.minecraft.class_3218.method_18765(class_3218.java:423)

-- Affected level --
Details:
	All players: 3 total; [class_3222['EDGW'/247, l='ServerLevel[world]', x=-587.35, y=68.00, z=338.48], class_3222['MAX_XiaoKui'/13780, l='ServerLevel[world]', x=117.48, y=103.62, z=216.71], class_3222['Nan_Yang'/185, l='ServerLevel[world]', x=-358.39, y=70.00, z=523.22]]
	Chunk stats: ServerChunkCache: 4230
	Level dimension: minecraft:overworld
	Level spawn location: World: (-43,63,239), Chunk: (at 5,3,15 in -3,14; contains blocks -48,0,224 to -33,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 480502354 game time, 505201746 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 168732 (now: false), thunder time: 22564 (now: false)
	Known server brands: vanilla, fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.class_3176.method_3813(class_3176.java:306)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.server.MinecraftServer.handler$zjb000$modifiedRunLoop(MinecraftServer.java:3796)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:653)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 3.10.0-1127.13.1.el7.x86_64
	Java Version: 1.8.0_252, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 476097256 bytes (454 MB) / 1101422592 bytes (1050 MB) up to 3723231232 bytes (3550 MB)
	CPUs: 4
	JVM Flags: 11 total; -Xincgc -Xss512K -XX:+AggressiveOpts -XX:+UseCompressedOops -XX:+UseFastAccessorMethods -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC -XX:-DisableExplicitGC -XX:-DisableExplicitGC -XX:TargetSurvivorRatio=90 -Xmx3584M
	Fabric Mods: 
		bbor: BoundingBoxOutlineReloaded 2.3-1.16.1
		carpet: Carpet Mod in Fabric 1.4.0
		carpet-extra: Carpet Extra 1.4.0
		com_github_shevek_parallelgzip: parallelgzip master-SNAPSHOT
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		fabric: Fabric API 0.16.2+build.385-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c02
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.6+a2d21ddd02
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.0+55e0cc5f02
		fabricloader: Fabric Loader 0.9.0+build.204
		here: here 0.0.10-mc1.16
		hopperoptimizations: Hopper Optimizations 0.2.1
		jankson: Jankson 3.0.0+j1.2.0
		lithium: Lithium 0.5.1-SNAPSHOT
		minecraft: Minecraft 1.16.1
		org_apache_commons_commons-compress: commons-compress 1.19
		org_tukaani_xz: xz 1.8
		phosphor: Phosphor 0.6.0+build.7
		textile_backup: Textile Backup 1.3.1-1.16.1
	Player Count: 3 / 24; [class_3222['Nan_Yang'/185, l='ServerLevel[world]', x=-358.39, y=70.00, z=523.22], class_3222['EDGW'/247, l='ServerLevel[world]', x=-587.35, y=68.00, z=338.48], class_3222['MAX_XiaoKui'/13780, l='ServerLevel[world]', x=117.48, y=103.62, z=216.71]]
	Data Packs: vanilla, file/bukkit, fabric/fabric-tool-attribute-api-v1, file/FZ.sDatapack-1.5.0-SNAPSHOT-dev.20200411.0751.zip (incompatible)
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
````

**Comment by DragonEggBedrockBreaking** [comment]
If 2No2Name fixed it you should close the issue.

**Comment by 2No2Name** [comment]
Assuming that the problem doesn't occur anymore after the fix, i'm closing this.
