### ISSUE TITLE
Incompatible with Terrestia?

### ISSUE THREAD

**Issue by he3als** [2No2Name/hopperOptimizations#30]
Incompatible with Terrestia?

```
[10:01:41] [Server thread/WARN]: Mixin apply failed mixins.terrestria.pathing.json:MixinLandPathNodeMaker -> net.minecraft.class_14: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("FIELD") on net/minecraft/class_14::terrestria$preventPathingIntoCustomCactuses with priority 1000 cannot inject into net/minecraft/class_14::method_58(Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;)Lnet/minecraft/class_7; merged by me.jellysquid.mods.lithium.mixin.ai.pathing.LandPathNodeMakerMixin with priority 1000 [ -> handler$zop000$terrestria$preventPathingIntoCustomCactuses(Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("FIELD") on net/minecraft/class_14::terrestria$preventPathingIntoCustomCactuses with priority 1000 cannot inject into net/minecraft/class_14::method_58(Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;)Lnet/minecraft/class_7; merged by me.jellysquid.mods.lithium.mixin.ai.pathing.LandPathNodeMakerMixin with priority 1000 [ -> handler$zop000$terrestria$preventPathingIntoCustomCactuses(Lnet/minecraft/class_1922;Lnet/minecraft/class_2338;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Prepare]
        at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at net.minecraft.class_1481.method_5965(class_1481.java:295) ~[intermediary-server.jar:?]
        at net.minecraft.class_1308.<init>(class_1308.java:133) ~[intermediary-server.jar:?]
        at net.minecraft.class_1314.<init>(class_1314.java:12) ~[intermediary-server.jar:?]
        at net.minecraft.class_1296.<init>(class_1296.java:28) ~[intermediary-server.jar:?]
        at net.minecraft.class_1429.<init>(class_1429.java:39) ~[intermediary-server.jar:?]
        at net.minecraft.class_1481.<init>(class_1481.java:82) ~[intermediary-server.jar:?]
        at net.minecraft.class_1299.method_5883(class_1299.java:463) ~[intermediary-server.jar:?]
        at net.minecraft.class_1299.method_17846(class_1299.java:472) ~[intermediary-server.jar:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at net.minecraft.class_1299.method_5892(class_1299.java:472) ~[intermediary-server.jar:?]
        at net.minecraft.class_1299.method_17848(class_1299.java:535) ~[intermediary-server.jar:?]
        at net.minecraft.class_1299.method_17842(class_1299.java:516) ~[intermediary-server.jar:?]
        at net.minecraft.class_2852.method_12386(class_2852.java:378) ~[intermediary-server.jar:?]
        at net.minecraft.class_2852.method_12388(class_2852.java:138) ~[intermediary-server.jar:?]
        at net.minecraft.class_2818.method_12206(class_2818.java:479) ~[intermediary-server.jar:?]
        at net.minecraft.class_3898.method_17227(class_3898.java:622) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[intermediary-server.jar:?]
        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[intermediary-server.jar:?]
        at net.minecraft.class_3898.method_20460(class_3898.java:611) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.class_3900.method_17634(class_3900.java:58) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:545) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server.jar:?]
        at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:554) ~[intermediary-server.jar:?]
        at net.minecraft.class_3215.method_19492(class_3215.java:280) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:749) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3774(MinecraftServer.java:505) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:338) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:179) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:645) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by DragonEggBedrockBreaking** [comment]
What version of 2no2name’s lithium fork are you using? It seems that is the issue. Does this still occur if you remove hopperoptimizations but keep 2no2name’s lithium fork?
